version: '3.8'

services:
  database:
    image: postgres:17
    container_name: manutencao_equipamentos_G2_database_container
    restart: always
    environment:
      POSTGRES_USER: usuarioG2
      POSTGRES_PASSWORD: passwordG2
      POSTGRES_DB: manutencao_equipamentos_G2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - manutencao_equipamentos_G2_data:/var/lib/postgresql/data

volumes:
  manutencao_equipamentos_G2_data: